- name: Push to Hugging Face (clean)
  env:
    HF_TOKEN: ${{ secrets.HF_TOKEN }}
  run: |
    set -e

    CURRENT_BRANCH=${GITHUB_REF_NAME}

    git config --global user.email "bot@github.com"
    git config --global user.name "GitHub Action"

    # удаляем картинки
    find . -type f \( -iname "*.png" -o -iname "*.jpg" -o -iname "*.jpeg" \) -delete

    # создаём чистую ветку БЕЗ истории
    git checkout --orphan clean-branch
    git add .
    git commit -m "clean commit (no images)"

    # пушим как нужную ветку
    git push --force https://robot:$HF_TOKEN@huggingface.co/spaces/qwefsdfsdsg/mdk clean-branch:${CURRENT_BRANCH}
