name: Sync to Hugging Face

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Prepare clean deploy directory
        run: |
          set -e

          rm -rf deploy
          mkdir deploy

          # копируем только backend в корень deploy
          cp -r back/* deploy/

          # (если есть Dockerfile в back)
          if [ -f back/Dockerfile ]; then
            cp back/Dockerfile deploy/Dockerfile
          fi

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          set -e

          git config --global user.email "bot@github.com"
          git config --global user.name "GitHub Action"

          cd deploy

          git init
          git add .
          git commit -m "deploy"

          git branch -M main

          git remote add hf https://robot:$HF_TOKEN@huggingface.co/spaces/qwefsdfsdsg/mdk

          git push --force hf main